### ISSUE TITLE
Barra de Carregamento eterna ao abrir o aplicativo

### ISSUE THREAD

**Issue by georgerappel** [RioBus/android-app#40]
Mesmo antes de fazer qualquer busca, há uma barra de carregamento eterna no topo, dando a impressão de que o aplicativo esta carregando algo.

A barra de carregamento **fica aparente enquanto o serviço de localização não te encontra**, ou seja, quando o GPS está desligado.

**Comment by georgerappel** [comment]
Só acontece quando a localização está desativada. Não fui encontrado, logo o mapa não mostrava minha localização e continuava com a barra de carregamento ativa.

**Comment by fmsouza** [comment]
No Android 6.0+ isso acontece por causa do problema relatado em #57.
